import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
//import './components';
import './home';
import './contact';
import './product';
import './category';
import './services';
import './login';
import './register';
import './passwordReset';
import './premium';
import './blog';


// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'app.layout',
  'app.home',
  'app.contact',
  'app.product',
  'app.category',
  'app.services',
  'app.login',
  'app.register',
  'app.passwordReset',
  'app.premium',
  'app.blog'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
